### ISSUE TITLE
Deploy application on neetoDeploy

### ISSUE THREAD

**Issue by muhsinfazal** [muhsinfazal/neeto-ui-challenge-by-muhsin-ahamed-fazal#9]

**Comment by muhsinfazal** [comment]
Deployed at [https://neetoui-challenge.neetoreviewapp.net/](https://neetoui-challenge.neetoreviewapp.net/)
Can be logged in using:
Username : oliver@example.com
Password : welcome

@yedhink @navaneethsdk Please review.

**Comment by navaneethsdk** [comment]
@muhsinfazal A few comments
- [x] Add a blank line after `useTranslation` for better readability. https://github.com/muhsinfazal/neeto-ui-challenge-by-muhsin-ahamed-fazal/blob/b352f15ba70a4cd2c6f95a3f32110188673758c1/app/javascript/src/components/Dashboard/Contacts/index.jsx#L14-L15
- [x] I can see these labels used at multiple places like in yup validation. Is there any specific reason why you haven't made them open to translations? https://github.com/muhsinfazal/neeto-ui-challenge-by-muhsin-ahamed-fazal/blob/b352f15ba70a4cd2c6f95a3f32110188673758c1/app/javascript/src/components/Dashboard/Contacts/index.jsx#L26
- [x] Let's expand `e` as `event`. https://github.com/muhsinfazal/neeto-ui-challenge-by-muhsin-ahamed-fazal/blob/b352f15ba70a4cd2c6f95a3f32110188673758c1/app/javascript/src/components/Dashboard/Contacts/index.jsx#L34
- [x] This does not seem to be right. Move this logic to `utils.js(x)` and name the function `buildContacts`. [Refer](https://academy.bigbinary.com/learn-react/react-best-practices/naming-conventions-in-react#when-to-use-the-render-keyword). https://github.com/muhsinfazal/neeto-ui-challenge-by-muhsin-ahamed-fazal/blob/b352f15ba70a4cd2c6f95a3f32110188673758c1/app/javascript/src/components/Dashboard/Contacts/Table/constants.jsx#L11-L16
- [x] Same as the above comment. https://github.com/muhsinfazal/neeto-ui-challenge-by-muhsin-ahamed-fazal/blob/b352f15ba70a4cd2c6f95a3f32110188673758c1/app/javascript/src/components/Dashboard/Contacts/Table/constants.jsx#L18-L50
- [x] Move this to a separate function prefixed with `render` keyword. https://github.com/muhsinfazal/neeto-ui-challenge-by-muhsin-ahamed-fazal/blob/b352f15ba70a4cd2c6f95a3f32110188673758c1/app/javascript/src/components/Dashboard/Contacts/Table/constants.jsx#L38-L47
- [x] Please change the placeholder to `Select contact`. https://github.com/muhsinfazal/neeto-ui-challenge-by-muhsin-ahamed-fazal/blob/b352f15ba70a4cd2c6f95a3f32110188673758c1/app/javascript/src/translation/en.json#L55-L58
